apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-music
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-music
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
      - name: SPRING_PROFILES_ACTIVE
        value: "mongodb"
      - name: JBP_CONFIG_OPEN_JDK_JRE
        value: "{\"jre\":{\"version\": \"11.+\"}}"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/evoila/spring-music
      ref:
        branch: master
